HTML_TAGS: dict[str, tuple[str, ...]] = {
    "html": ("lang", "dir", "xmlns", "manifest"),
    "head": (),
    "title": (),
    "base": ("href", "target"),
    "link": (
        "rel",
        "href",
        "type",
        "media",
        "sizes",
        "hreflang",
        "crossorigin",
        "integrity",
        "referrerpolicy",
        "as",
        "color",
        "disabled",
        "imagesizes",
        "imagesrcset",
    ),
    "meta": ("name", "content", "charset", "http-equiv", "property", "scheme"),
    "style": ("type", "media", "scoped", "title", "disabled"),
    "script": (
        "src",
        "type",
        "charset",
        "async",
        "defer",
        "crossorigin",
        "integrity",
        "nomodule",
        "referrerpolicy",
        "fetchpriority",
    ),
    "noscript": (),
    "body": (
        "onload",
        "onunload",
        "onbeforeunload",
        "onhashchange",
        "onmessage",
        "onoffline",
        "ononline",
        "onpagehide",
        "onpageshow",
        "onpopstate",
        "onresize",
        "onstorage",
        "onunhandledrejection",
    ),
    "section": (),
    "nav": (),
    "article": (),
    "aside": (),
    "h1": (),
    "h2": (),
    "h3": (),
    "h4": (),
    "h5": (),
    "h6": (),
    "hgroup": (),
    "header": (),
    "footer": (),
    "address": (),
    "p": (),
    "hr": (),
    "pre": ("width",),
    "blockquote": ("cite",),
    "ol": ("reversed", "start", "type"),
    "ul": (),
    "menu": ("type", "label"),
    "li": ("value",),
    "dl": (),
    "dt": (),
    "dd": (),
    "figure": (),
    "figcaption": (),
    "main": (),
    "div": (),
    "a": (
        "href",
        "target",
        "download",
        "ping",
        "rel",
        "hreflang",
        "type",
        "referrerpolicy",
    ),
    "em": (),
    "strong": (),
    "small": (),
    "s": (),
    "cite": (),
    "q": ("cite",),
    "dfn": (),
    "abbr": (),
    "ruby": (),
    "rt": (),
    "rp": (),
    "data": ("value",),
    "time": ("datetime",),
    "code": (),
    "var": (),
    "samp": (),
    "kbd": (),
    "sub": (),
    "sup": (),
    "i": (),
    "b": (),
    "u": (),
    "mark": (),
    "bdi": (),
    "bdo": ("dir",),
    "span": (),
    "ins": ("cite", "datetime"),
    "del": ("cite", "datetime"),
    "picture": (),
    "img": (
        "src",
        "alt",
        "srcset",
        "sizes",
        "crossorigin",
        "usemap",
        "ismap",
        "width",
        "height",
        "referrerpolicy",
        "decoding",
        "loading",
        "fetchpriority",
    ),
    "iframe": (
        "src",
        "srcdoc",
        "name",
        "sandbox",
        "allow",
        "allowfullscreen",
        "width",
        "height",
        "referrerpolicy",
        "loading",
    ),
    "embed": ("src", "type", "width", "height"),
    "object": ("data", "type", "name", "usemap", "form", "width", "height"),
    "video": (
        "src",
        "crossorigin",
        "poster",
        "preload",
        "autoplay",
        "playsinline",
        "loop",
        "muted",
        "controls",
        "width",
        "height",
    ),
    "audio": ("src", "crossorigin", "preload", "autoplay", "loop", "muted", "controls"),
    "source": ("src", "type", "srcset", "sizes", "media", "width", "height"),
    "track": ("default", "kind", "label", "src", "srclang"),
    "canvas": ("width", "height"),
    "map": ("name",),
    "area": (
        "alt",
        "coords",
        "shape",
        "href",
        "target",
        "download",
        "ping",
        "rel",
        "referrerpolicy",
    ),
    "svg": ("xmlns", "width", "height", "viewBox", "preserveAspectRatio"),
    "math": ("xmlns",),
    "table": (),
    "caption": (),
    "colgroup": ("span",),
    "col": ("span",),
    "tbody": (),
    "thead": (),
    "tfoot": (),
    "tr": (),
    "td": ("colspan", "rowspan", "headers"),
    "th": ("colspan", "rowspan", "headers", "scope", "abbr"),
    "form": (
        "accept-charset",
        "action",
        "autocomplete",
        "enctype",
        "method",
        "name",
        "novalidate",
        "target",
        "rel",
    ),
    "label": ("for",),
    "input": (
        "accept",
        "alt",
        "autocomplete",
        "checked",
        "dirname",
        "disabled",
        "form",
        "formaction",
        "formenctype",
        "formmethod",
        "formnovalidate",
        "formtarget",
        "height",
        "list",
        "max",
        "maxlength",
        "min",
        "minlength",
        "multiple",
        "name",
        "pattern",
        "placeholder",
        "popovertarget",
        "popovertargetaction",
        "readonly",
        "required",
        "size",
        "src",
        "step",
        "type",
        "value",
        "width",
    ),
    "button": (
        "disabled",
        "form",
        "formaction",
        "formenctype",
        "formmethod",
        "formnovalidate",
        "formtarget",
        "name",
        "popovertarget",
        "popovertargetaction",
        "type",
        "value",
    ),
    "select": (
        "autocomplete",
        "disabled",
        "form",
        "multiple",
        "name",
        "required",
        "size",
    ),
    "datalist": (),
    "optgroup": ("disabled", "label"),
    "option": ("disabled", "label", "selected", "value"),
    "textarea": (
        "autocomplete",
        "cols",
        "dirname",
        "disabled",
        "form",
        "maxlength",
        "minlength",
        "name",
        "placeholder",
        "readonly",
        "required",
        "rows",
        "wrap",
    ),
    "output": ("for", "form", "name"),
    "progress": ("value", "max"),
    "meter": ("value", "min", "max", "low", "high", "optimum"),
    "fieldset": ("disabled", "form", "name"),
    "legend": (),
    "details": ("open",),
    "summary": (),
    "dialog": ("open",),
    "slot": ("name",),
    "template": (),
}

# Self-closing (void) HTML tags
SELF_CLOSING_TAGS: dict[str, tuple[str, ...]] = {
    "area": (
        "alt",
        "coords",
        "shape",
        "href",
        "target",
        "download",
        "ping",
        "rel",
        "referrerpolicy",
    ),
    "base": ("href", "target"),
    "br": (),
    "col": ("span",),
    "embed": ("src", "type", "width", "height"),
    "hr": (),
    "img": (
        "src",
        "alt",
        "srcset",
        "sizes",
        "crossorigin",
        "usemap",
        "ismap",
        "width",
        "height",
        "referrerpolicy",
        "decoding",
        "loading",
        "fetchpriority",
    ),
    "input": (
        "accept",
        "alt",
        "autocomplete",
        "checked",
        "dirname",
        "disabled",
        "form",
        "formaction",
        "formenctype",
        "formmethod",
        "formnovalidate",
        "formtarget",
        "height",
        "list",
        "max",
        "maxlength",
        "min",
        "minlength",
        "multiple",
        "name",
        "pattern",
        "placeholder",
        "popovertarget",
        "popovertargetaction",
        "readonly",
        "required",
        "size",
        "src",
        "step",
        "type",
        "value",
        "width",
    ),
    "link": (
        "rel",
        "href",
        "type",
        "media",
        "sizes",
        "hreflang",
        "crossorigin",
        "integrity",
        "referrerpolicy",
        "as",
        "color",
        "disabled",
        "imagesizes",
        "imagesrcset",
    ),
    "meta": ("name", "content", "charset", "http-equiv", "property", "scheme"),
    "param": ("name", "value"),
    "source": ("src", "type", "srcset", "sizes", "media", "width", "height"),
    "track": ("default", "kind", "label", "src", "srclang"),
    "wbr": (),
}

GLOBAL_ATTRIBUTES = (
    "accesskey",
    "autocapitalize",
    "autofocus",
    "class",
    "contenteditable",
    "contextmenu",
    "dir",
    "draggable",
    "enterkeyhint",
    "exportparts",
    "hidden",
    "id",
    "inert",
    "inputmode",
    "is",
    "itemid",
    "itemprop",
    "itemref",
    "itemscope",
    "itemtype",
    "lang",
    "nonce",
    "part",
    "popover",
    "role",
    "slot",
    "spellcheck",
    "style",
    "tabindex",
    "title",
    "translate",
    "virtualkeyboardpolicy",
)

# Event handler attributes (начинающиеся с "on")
EVENT_ATTRIBUTES = (
    "onabort",
    "onafterprint",
    "onbeforeprint",
    "onbeforeunload",
    "onblur",
    "oncanplay",
    "oncanplaythrough",
    "onchange",
    "onclick",
    "oncontextmenu",
    "oncopy",
    "oncuechange",
    "oncut",
    "ondblclick",
    "ondrag",
    "ondragend",
    "ondragenter",
    "ondragleave",
    "ondragover",
    "ondragstart",
    "ondrop",
    "ondurationchange",
    "onemptied",
    "onended",
    "onerror",
    "onfocus",
    "onhashchange",
    "oninput",
    "oninvalid",
    "onkeydown",
    "onkeypress",
    "onkeyup",
    "onload",
    "onloadeddata",
    "onloadedmetadata",
    "onloadstart",
    "onmessage",
    "onmousedown",
    "onmousemove",
    "onmouseout",
    "onmouseover",
    "onmouseup",
    "onmousewheel",
    "onoffline",
    "ononline",
    "onpagehide",
    "onpageshow",
    "onpaste",
    "onpause",
    "onplay",
    "onplaying",
    "onpopstate",
    "onprogress",
    "onratechange",
    "onreset",
    "onresize",
    "onscroll",
    "onsearch",
    "onseeked",
    "onseeking",
    "onselect",
    "onstalled",
    "onstorage",
    "onsubmit",
    "onsuspend",
    "ontimeupdate",
    "ontoggle",
    "onunload",
    "onvolumechange",
    "onwaiting",
    "onwheel",
)
