name: Publish to PyPI

on:
    release:
        types: [published]
    workflow_dispatch:

jobs:
    lint-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - name: Install uv
              uses: astral-sh/setup-uv@v3

            - name: Install dependencies
              run: |
                  uv sync --all-extras

            - name: Run Ruff linter
              run: |
                  uv run ruff check .

            - name: Run Ruff formatter check
              run: |
                  uv run ruff format --check .

            - name: Run mypy
              run: |
                  uv run mypy html_conv/ --ignore-missing-imports

            - name: Run tests
              run: |
                  uv run pytest tests/ --cov=html_conv --cov-report=xml --cov-report=term

    build:
        needs: lint-and-test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - name: Install uv
              uses: astral-sh/setup-uv@v3

            - name: Install build dependencies
              run: |
                  uv pip install --system build

            - name: Build package
              run: |
                  python -m build

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist/

    publish:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: dist/

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  password: ${{ secrets.PYPI_API_TOKEN }}
